# Generated by Django 5.2.4 on 2025-07-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role_doctorprofile_patientprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='specialty',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='core.specialty'),
        ),
    ]
