# Generated by Django 5.2.4 on 2025-07-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_specialty_remove_doctorprofile_specialty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
